/**
 * Countries Data - Real data from Worldometers (2025)
 * Source: https://www.worldometers.info/geography/countries-of-the-world/
 */

export const countriesData = [
  // Top 50 by population with real data
  { id: 'c-ind', code: 'IND', name: 'India', region: 'Asia', incomeLevel: 'lower-middle', population: 1463865525 },
  { id: 'c-chn', code: 'CHN', name: 'China', region: 'Asia', incomeLevel: 'upper-middle', population: 1416096094 },
  { id: 'c-usa', code: 'USA', name: 'United States', region: 'Northern America', incomeLevel: 'high', population: 347275807 },
  { id: 'c-idn', code: 'IDN', name: 'Indonesia', region: 'Asia', incomeLevel: 'upper-middle', population: 285721236 },
  { id: 'c-pak', code: 'PAK', name: 'Pakistan', region: 'Asia', incomeLevel: 'lower-middle', population: 255219554 },
  { id: 'c-nga', code: 'NGA', name: 'Nigeria', region: 'Africa', incomeLevel: 'lower-middle', population: 237527782 },
  { id: 'c-bra', code: 'BRA', name: 'Brazil', region: 'Latin America', incomeLevel: 'upper-middle', population: 212812405 },
  { id: 'c-bgd', code: 'BGD', name: 'Bangladesh', region: 'Asia', incomeLevel: 'lower-middle', population: 175686899 },
  { id: 'c-rus', code: 'RUS', name: 'Russia', region: 'Europe', incomeLevel: 'upper-middle', population: 143997393 },
  { id: 'c-eth', code: 'ETH', name: 'Ethiopia', region: 'Africa', incomeLevel: 'low', population: 135472051 },
  { id: 'c-mex', code: 'MEX', name: 'Mexico', region: 'Latin America', incomeLevel: 'upper-middle', population: 131946900 },
  { id: 'c-jpn', code: 'JPN', name: 'Japan', region: 'Asia', incomeLevel: 'high', population: 123103479 },
  { id: 'c-egy', code: 'EGY', name: 'Egypt', region: 'Africa', incomeLevel: 'lower-middle', population: 118365995 },
  { id: 'c-phl', code: 'PHL', name: 'Philippines', region: 'Asia', incomeLevel: 'lower-middle', population: 116786962 },
  { id: 'c-cod', code: 'COD', name: 'DR Congo', region: 'Africa', incomeLevel: 'low', population: 112832473 },
  { id: 'c-vnm', code: 'VNM', name: 'Vietnam', region: 'Asia', incomeLevel: 'lower-middle', population: 101598527 },
  { id: 'c-irn', code: 'IRN', name: 'Iran', region: 'Asia', incomeLevel: 'lower-middle', population: 92417681 },
  { id: 'c-tur', code: 'TUR', name: 'Turkey', region: 'Asia', incomeLevel: 'upper-middle', population: 87685426 },
  { id: 'c-deu', code: 'DEU', name: 'Germany', region: 'Europe', incomeLevel: 'high', population: 84075075 },
  { id: 'c-tha', code: 'THA', name: 'Thailand', region: 'Asia', incomeLevel: 'upper-middle', population: 71619863 },
  { id: 'c-tza', code: 'TZA', name: 'Tanzania', region: 'Africa', incomeLevel: 'lower-middle', population: 70545865 },
  { id: 'c-gbr', code: 'GBR', name: 'United Kingdom', region: 'Europe', incomeLevel: 'high', population: 69551332 },
  { id: 'c-fra', code: 'FRA', name: 'France', region: 'Europe', incomeLevel: 'high', population: 66650804 },
  { id: 'c-zaf', code: 'ZAF', name: 'South Africa', region: 'Africa', incomeLevel: 'upper-middle', population: 64747319 },
  { id: 'c-ita', code: 'ITA', name: 'Italy', region: 'Europe', incomeLevel: 'high', population: 59146260 },
  { id: 'c-ken', code: 'KEN', name: 'Kenya', region: 'Africa', incomeLevel: 'lower-middle', population: 57532493 },
  { id: 'c-mmr', code: 'MMR', name: 'Myanmar', region: 'Asia', incomeLevel: 'lower-middle', population: 54850648 },
  { id: 'c-col', code: 'COL', name: 'Colombia', region: 'Latin America', incomeLevel: 'upper-middle', population: 53425635 },
  { id: 'c-kor', code: 'KOR', name: 'South Korea', region: 'Asia', incomeLevel: 'high', population: 51667029 },
  { id: 'c-sdn', code: 'SDN', name: 'Sudan', region: 'Africa', incomeLevel: 'low', population: 51662147 },
  { id: 'c-uga', code: 'UGA', name: 'Uganda', region: 'Africa', incomeLevel: 'low', population: 51384894 },
  { id: 'c-esp', code: 'ESP', name: 'Spain', region: 'Europe', incomeLevel: 'high', population: 47889958 },
  { id: 'c-dza', code: 'DZA', name: 'Algeria', region: 'Africa', incomeLevel: 'lower-middle', population: 47435312 },
  { id: 'c-irq', code: 'IRQ', name: 'Iraq', region: 'Asia', incomeLevel: 'upper-middle', population: 47020774 },
  { id: 'c-arg', code: 'ARG', name: 'Argentina', region: 'Latin America', incomeLevel: 'upper-middle', population: 45851378 },
  { id: 'c-afg', code: 'AFG', name: 'Afghanistan', region: 'Asia', incomeLevel: 'low', population: 43844111 },
  { id: 'c-yem', code: 'YEM', name: 'Yemen', region: 'Asia', incomeLevel: 'low', population: 41773878 },
  { id: 'c-can', code: 'CAN', name: 'Canada', region: 'Northern America', incomeLevel: 'high', population: 40126723 },
  { id: 'c-ago', code: 'AGO', name: 'Angola', region: 'Africa', incomeLevel: 'lower-middle', population: 39040039 },
  { id: 'c-ukr', code: 'UKR', name: 'Ukraine', region: 'Europe', incomeLevel: 'lower-middle', population: 38980376 },
  { id: 'c-mar', code: 'MAR', name: 'Morocco', region: 'Africa', incomeLevel: 'lower-middle', population: 38430770 },
  { id: 'c-pol', code: 'POL', name: 'Poland', region: 'Europe', incomeLevel: 'high', population: 38140910 },
  { id: 'c-uzb', code: 'UZB', name: 'Uzbekistan', region: 'Asia', incomeLevel: 'lower-middle', population: 37053428 },
  { id: 'c-mys', code: 'MYS', name: 'Malaysia', region: 'Asia', incomeLevel: 'upper-middle', population: 35977838 },
  { id: 'c-moz', code: 'MOZ', name: 'Mozambique', region: 'Africa', incomeLevel: 'low', population: 35631653 },
  { id: 'c-gha', code: 'GHA', name: 'Ghana', region: 'Africa', incomeLevel: 'lower-middle', population: 35064272 },
  { id: 'c-per', code: 'PER', name: 'Peru', region: 'Latin America', incomeLevel: 'upper-middle', population: 34576665 },
  { id: 'c-sau', code: 'SAU', name: 'Saudi Arabia', region: 'Asia', incomeLevel: 'high', population: 34566328 },
  { id: 'c-mdg', code: 'MDG', name: 'Madagascar', region: 'Africa', incomeLevel: 'low', population: 32740678 },
  { id: 'c-civ', code: 'CIV', name: 'Ivory Coast', region: 'Africa', incomeLevel: 'lower-middle', population: 32711547 },
  { id: 'c-npl', code: 'NPL', name: 'Nepal', region: 'Asia', incomeLevel: 'lower-middle', population: 29618118 },
  { id: 'c-ven', code: 'VEN', name: 'Venezuela', region: 'Latin America', incomeLevel: 'upper-middle', population: 28516896 },
  { id: 'c-aus', code: 'AUS', name: 'Australia', region: 'Oceania', incomeLevel: 'high', population: 26974026 },
  { id: 'c-prk', code: 'PRK', name: 'North Korea', region: 'Asia', incomeLevel: 'low', population: 26571036 },
  { id: 'c-lka', code: 'LKA', name: 'Sri Lanka', region: 'Asia', incomeLevel: 'lower-middle', population: 23229470 },
  { id: 'c-kaz', code: 'KAZ', name: 'Kazakhstan', region: 'Asia', incomeLevel: 'upper-middle', population: 20843754 },
  { id: 'c-chl', code: 'CHL', name: 'Chile', region: 'Latin America', incomeLevel: 'high', population: 19859921 },
  { id: 'c-rou', code: 'ROU', name: 'Romania', region: 'Europe', incomeLevel: 'upper-middle', population: 18908650 },
  { id: 'c-nld', code: 'NLD', name: 'Netherlands', region: 'Europe', incomeLevel: 'high', population: 18346819 },
  { id: 'c-ecu', code: 'ECU', name: 'Ecuador', region: 'Latin America', incomeLevel: 'upper-middle', population: 18289896 },
  { id: 'c-khm', code: 'KHM', name: 'Cambodia', region: 'Asia', incomeLevel: 'lower-middle', population: 17847982 },
  { id: 'c-zwe', code: 'ZWE', name: 'Zimbabwe', region: 'Africa', incomeLevel: 'lower-middle', population: 16950795 },
  { id: 'c-rwa', code: 'RWA', name: 'Rwanda', region: 'Africa', incomeLevel: 'low', population: 14569341 },
  { id: 'c-tun', code: 'TUN', name: 'Tunisia', region: 'Africa', incomeLevel: 'lower-middle', population: 12348573 },
  { id: 'c-bel', code: 'BEL', name: 'Belgium', region: 'Europe', incomeLevel: 'high', population: 11758603 },
  { id: 'c-jor', code: 'JOR', name: 'Jordan', region: 'Asia', incomeLevel: 'upper-middle', population: 11520684 },
  { id: 'c-dom', code: 'DOM', name: 'Dominican Republic', region: 'Latin America', incomeLevel: 'upper-middle', population: 11520487 },
  { id: 'c-are', code: 'ARE', name: 'United Arab Emirates', region: 'Asia', incomeLevel: 'high', population: 11346000 },
  { id: 'c-cub', code: 'CUB', name: 'Cuba', region: 'Latin America', incomeLevel: 'upper-middle', population: 10937203 },
  { id: 'c-tjk', code: 'TJK', name: 'Tajikistan', region: 'Asia', incomeLevel: 'lower-middle', population: 10786734 },
  { id: 'c-swe', code: 'SWE', name: 'Sweden', region: 'Europe', incomeLevel: 'high', population: 10656633 },
  { id: 'c-cze', code: 'CZE', name: 'Czech Republic', region: 'Europe', incomeLevel: 'high', population: 10609239 },
  { id: 'c-prt', code: 'PRT', name: 'Portugal', region: 'Europe', incomeLevel: 'high', population: 10411834 },
  { id: 'c-aze', code: 'AZE', name: 'Azerbaijan', region: 'Asia', incomeLevel: 'upper-middle', population: 10397713 },
  { id: 'c-grc', code: 'GRC', name: 'Greece', region: 'Europe', incomeLevel: 'high', population: 9938844 },
  { id: 'c-hun', code: 'HUN', name: 'Hungary', region: 'Europe', incomeLevel: 'high', population: 9632287 },
  { id: 'c-isr', code: 'ISR', name: 'Israel', region: 'Asia', incomeLevel: 'high', population: 9517181 },
  { id: 'c-aut', code: 'AUT', name: 'Austria', region: 'Europe', incomeLevel: 'high', population: 9113574 },
  { id: 'c-blr', code: 'BLR', name: 'Belarus', region: 'Europe', incomeLevel: 'upper-middle', population: 8997603 },
  { id: 'c-che', code: 'CHE', name: 'Switzerland', region: 'Europe', incomeLevel: 'high', population: 8967407 },
  { id: 'c-lao', code: 'LAO', name: 'Laos', region: 'Asia', incomeLevel: 'lower-middle', population: 7873046 },
  { id: 'c-tkm', code: 'TKM', name: 'Turkmenistan', region: 'Asia', incomeLevel: 'upper-middle', population: 7618847 },
  { id: 'c-kgz', code: 'KGZ', name: 'Kyrgyzstan', region: 'Asia', incomeLevel: 'lower-middle', population: 7295034 },
  { id: 'c-pry', code: 'PRY', name: 'Paraguay', region: 'Latin America', incomeLevel: 'upper-middle', population: 7013078 },
  { id: 'c-bgr', code: 'BGR', name: 'Bulgaria', region: 'Europe', incomeLevel: 'upper-middle', population: 6714560 },
  { id: 'c-srb', code: 'SRB', name: 'Serbia', region: 'Europe', incomeLevel: 'upper-middle', population: 6689039 },
  { id: 'c-dnk', code: 'DNK', name: 'Denmark', region: 'Europe', incomeLevel: 'high', population: 6002507 },
  { id: 'c-sgp', code: 'SGP', name: 'Singapore', region: 'Asia', incomeLevel: 'high', population: 5870750 },
  { id: 'c-lbn', code: 'LBN', name: 'Lebanon', region: 'Asia', incomeLevel: 'lower-middle', population: 5849421 },
  { id: 'c-fin', code: 'FIN', name: 'Finland', region: 'Europe', incomeLevel: 'high', population: 5623329 },
  { id: 'c-nor', code: 'NOR', name: 'Norway', region: 'Europe', incomeLevel: 'high', population: 5623071 },
  { id: 'c-omn', code: 'OMN', name: 'Oman', region: 'Asia', incomeLevel: 'high', population: 5494691 },
  { id: 'c-svk', code: 'SVK', name: 'Slovakia', region: 'Europe', incomeLevel: 'high', population: 5474881 },
  { id: 'c-irl', code: 'IRL', name: 'Ireland', region: 'Europe', incomeLevel: 'high', population: 5308039 },
  { id: 'c-nzl', code: 'NZL', name: 'New Zealand', region: 'Oceania', incomeLevel: 'high', population: 5251899 },
  { id: 'c-cri', code: 'CRI', name: 'Costa Rica', region: 'Latin America', incomeLevel: 'upper-middle', population: 5152950 },
  { id: 'c-kwt', code: 'KWT', name: 'Kuwait', region: 'Asia', incomeLevel: 'high', population: 5026078 },
  { id: 'c-pan', code: 'PAN', name: 'Panama', region: 'Latin America', incomeLevel: 'high', population: 4571189 },
  { id: 'c-hrv', code: 'HRV', name: 'Croatia', region: 'Europe', incomeLevel: 'high', population: 3848160 },
  { id: 'c-geo', code: 'GEO', name: 'Georgia', region: 'Asia', incomeLevel: 'upper-middle', population: 3806671 },
  { id: 'c-mng', code: 'MNG', name: 'Mongolia', region: 'Asia', incomeLevel: 'lower-middle', population: 3517100 },
  { id: 'c-ury', code: 'URY', name: 'Uruguay', region: 'Latin America', incomeLevel: 'high', population: 3384688 },
  { id: 'c-bih', code: 'BIH', name: 'Bosnia and Herzegovina', region: 'Europe', incomeLevel: 'upper-middle', population: 3140095 },
  { id: 'c-qat', code: 'QAT', name: 'Qatar', region: 'Asia', incomeLevel: 'high', population: 3115889 },
  { id: 'c-nam', code: 'NAM', name: 'Namibia', region: 'Africa', incomeLevel: 'upper-middle', population: 3092816 },
  { id: 'c-mda', code: 'MDA', name: 'Moldova', region: 'Europe', incomeLevel: 'upper-middle', population: 2996106 },
  { id: 'c-arm', code: 'ARM', name: 'Armenia', region: 'Asia', incomeLevel: 'upper-middle', population: 2952365 },
  { id: 'c-jam', code: 'JAM', name: 'Jamaica', region: 'Latin America', incomeLevel: 'upper-middle', population: 2837077 },
  { id: 'c-ltu', code: 'LTU', name: 'Lithuania', region: 'Europe', incomeLevel: 'high', population: 2830144 },
  { id: 'c-alb', code: 'ALB', name: 'Albania', region: 'Europe', incomeLevel: 'upper-middle', population: 2771508 },
  { id: 'c-bwa', code: 'BWA', name: 'Botswana', region: 'Africa', incomeLevel: 'upper-middle', population: 2562122 },
  { id: 'c-svn', code: 'SVN', name: 'Slovenia', region: 'Europe', incomeLevel: 'high', population: 2117072 },
  { id: 'c-lva', code: 'LVA', name: 'Latvia', region: 'Europe', incomeLevel: 'high', population: 1853559 },
  { id: 'c-mkd', code: 'MKD', name: 'North Macedonia', region: 'Europe', incomeLevel: 'upper-middle', population: 1813791 },
  { id: 'c-bhr', code: 'BHR', name: 'Bahrain', region: 'Asia', incomeLevel: 'high', population: 1643332 },
  { id: 'c-tto', code: 'TTO', name: 'Trinidad and Tobago', region: 'Latin America', incomeLevel: 'high', population: 1511155 },
  { id: 'c-cyp', code: 'CYP', name: 'Cyprus', region: 'Europe', incomeLevel: 'high', population: 1370754 },
  { id: 'c-est', code: 'EST', name: 'Estonia', region: 'Europe', incomeLevel: 'high', population: 1344232 },
  { id: 'c-mus', code: 'MUS', name: 'Mauritius', region: 'Africa', incomeLevel: 'upper-middle', population: 1268280 },
  { id: 'c-btn', code: 'BTN', name: 'Bhutan', region: 'Asia', incomeLevel: 'lower-middle', population: 796682 },
  { id: 'c-lux', code: 'LUX', name: 'Luxembourg', region: 'Europe', incomeLevel: 'high', population: 680453 },
  { id: 'c-mne', code: 'MNE', name: 'Montenegro', region: 'Europe', incomeLevel: 'upper-middle', population: 632729 },
  { id: 'c-mlt', code: 'MLT', name: 'Malta', region: 'Europe', incomeLevel: 'high', population: 545405 },
  { id: 'c-mdv', code: 'MDV', name: 'Maldives', region: 'Asia', incomeLevel: 'upper-middle', population: 529676 },
  { id: 'c-brn', code: 'BRN', name: 'Brunei', region: 'Asia', incomeLevel: 'high', population: 466330 },
  { id: 'c-isl', code: 'ISL', name: 'Iceland', region: 'Europe', incomeLevel: 'high', population: 398266 },
  { id: 'c-sen', code: 'SEN', name: 'Senegal', region: 'Africa', incomeLevel: 'lower-middle', population: 18275743 },
  // Additional countries for comprehensive index coverage
  { id: 'c-gtm', code: 'GTM', name: 'Guatemala', region: 'Latin America', incomeLevel: 'upper-middle', population: 18275743 },
  { id: 'c-bol', code: 'BOL', name: 'Bolivia', region: 'Latin America', incomeLevel: 'lower-middle', population: 12186079 },
  { id: 'c-ben', code: 'BEN', name: 'Benin', region: 'Africa', incomeLevel: 'lower-middle', population: 13712828 },
  { id: 'c-cmr', code: 'CMR', name: 'Cameroon', region: 'Africa', incomeLevel: 'lower-middle', population: 28647293 },
  { id: 'c-mrt', code: 'MRT', name: 'Mauritania', region: 'Africa', incomeLevel: 'lower-middle', population: 4862989 },
  { id: 'c-mwi', code: 'MWI', name: 'Malawi', region: 'Africa', incomeLevel: 'low', population: 21473304 },
  { id: 'c-nic', code: 'NIC', name: 'Nicaragua', region: 'Latin America', incomeLevel: 'lower-middle', population: 7046310 },
  { id: 'c-png', code: 'PNG', name: 'Papua New Guinea', region: 'Oceania', incomeLevel: 'lower-middle', population: 10329931 },
  { id: 'c-tls', code: 'TLS', name: 'Timor-Leste', region: 'Asia', incomeLevel: 'lower-middle', population: 1360596 },
  { id: 'c-zmb', code: 'ZMB', name: 'Zambia', region: 'Africa', incomeLevel: 'lower-middle', population: 20569737 },
  // Additional countries for complete ranking coverage
  { id: 'c-hkg', code: 'HKG', name: 'Hong Kong', region: 'Asia', incomeLevel: 'high', population: 7413100 },
  { id: 'c-twn', code: 'TWN', name: 'Taiwan', region: 'Asia', incomeLevel: 'high', population: 23894394 },
  { id: 'c-lie', code: 'LIE', name: 'Liechtenstein', region: 'Europe', incomeLevel: 'high', population: 39870 },
  { id: 'c-brb', code: 'BRB', name: 'Barbados', region: 'Latin America', incomeLevel: 'high', population: 281995 },
  { id: 'c-caf', code: 'CAF', name: 'Central African Republic', region: 'Africa', incomeLevel: 'low', population: 5742315 },
  { id: 'c-hti', code: 'HTI', name: 'Haiti', region: 'Latin America', incomeLevel: 'lower-middle', population: 11724763 },
  { id: 'c-lby', code: 'LBY', name: 'Libya', region: 'Africa', incomeLevel: 'upper-middle', population: 7361263 },
  { id: 'c-ner', code: 'NER', name: 'Niger', region: 'Africa', incomeLevel: 'low', population: 27202843 },
  { id: 'c-som', code: 'SOM', name: 'Somalia', region: 'Africa', incomeLevel: 'low', population: 18143379 },
  { id: 'c-ssd', code: 'SSD', name: 'South Sudan', region: 'Africa', incomeLevel: 'low', population: 11943408 },
  { id: 'c-syr', code: 'SYR', name: 'Syria', region: 'Asia', incomeLevel: 'low', population: 23865423 },
  { id: 'c-tcd', code: 'TCD', name: 'Chad', region: 'Africa', incomeLevel: 'low', population: 18523165 },
  // Alternative codes used in some rankings (pointing to same countries)
  { id: 'c-bot', code: 'BOT', name: 'Botswana (alt)', region: 'Africa', incomeLevel: 'upper-middle', population: 2562122 },
  { id: 'c-lat', code: 'LAT', name: 'Latvia (alt)', region: 'Europe', incomeLevel: 'high', population: 1853559 },
  { id: 'c-uae', code: 'UAE', name: 'United Arab Emirates (alt)', region: 'Asia', incomeLevel: 'high', population: 11346000 },
  { id: 'c-pri', code: 'PRI', name: 'Puerto Rico', region: 'Latin America', incomeLevel: 'high', population: 3205691 },
  // Additional countries needed for new indices
  { id: 'c-gmb', code: 'GMB', name: 'Gambia', region: 'Africa', incomeLevel: 'low', population: 2705568 },
  { id: 'c-mli', code: 'MLI', name: 'Mali', region: 'Africa', incomeLevel: 'low', population: 23293698 },
  { id: 'c-bdi', code: 'BDI', name: 'Burundi', region: 'Africa', incomeLevel: 'low', population: 13238559 },
  { id: 'c-sle', code: 'SLE', name: 'Sierra Leone', region: 'Africa', incomeLevel: 'low', population: 8791092 },
  { id: 'c-lbr', code: 'LBR', name: 'Liberia', region: 'Africa', incomeLevel: 'low', population: 5418377 },
  { id: 'c-vut', code: 'VUT', name: 'Vanuatu', region: 'Oceania', incomeLevel: 'lower-middle', population: 334506 },
  { id: 'c-hnd', code: 'HND', name: 'Honduras', region: 'Latin America', incomeLevel: 'lower-middle', population: 10593798 },
  { id: 'c-eri', code: 'ERI', name: 'Eritrea', region: 'Africa', incomeLevel: 'low', population: 3748901 },
  // Additional countries for new indices - December 2025
  { id: 'c-mco', code: 'MCO', name: 'Monaco', region: 'Europe', incomeLevel: 'high', population: 39050 },
  { id: 'c-fsm', code: 'FSM', name: 'Micronesia', region: 'Oceania', incomeLevel: 'lower-middle', population: 115021 },
  { id: 'c-kir', code: 'KIR', name: 'Kiribati', region: 'Oceania', incomeLevel: 'lower-middle', population: 131536 },
  { id: 'c-slv', code: 'SLV', name: 'El Salvador', region: 'Latin America', incomeLevel: 'lower-middle', population: 6314167 },
  { id: 'c-gab', code: 'GAB', name: 'Gabon', region: 'Africa', incomeLevel: 'upper-middle', population: 2436566 },
  { id: 'c-vct', code: 'VCT', name: 'St. Vincent and the Grenadines', region: 'Latin America', incomeLevel: 'upper-middle', population: 104332 },
  { id: 'c-blz', code: 'BLZ', name: 'Belize', region: 'Latin America', incomeLevel: 'upper-middle', population: 410825 },
  { id: 'c-gnq', code: 'GNQ', name: 'Equatorial Guinea', region: 'Africa', incomeLevel: 'upper-middle', population: 1714671 },
  { id: 'c-lso', code: 'LSO', name: 'Lesotho', region: 'Africa', incomeLevel: 'lower-middle', population: 2210000 },
  { id: 'c-swz', code: 'SWZ', name: 'Eswatini', region: 'Africa', incomeLevel: 'lower-middle', population: 1210822 },
  { id: 'c-bfa', code: 'BFA', name: 'Burkina Faso', region: 'Africa', incomeLevel: 'low', population: 23251485 },
  { id: 'c-fji', code: 'FJI', name: 'Fiji', region: 'Oceania', incomeLevel: 'upper-middle', population: 936375 },
  // Additional countries for World Risk Index
  { id: 'c-slb', code: 'SLB', name: 'Solomon Islands', region: 'Oceania', incomeLevel: 'lower-middle', population: 740424 },
  { id: 'c-dji', code: 'DJI', name: 'Djibouti', region: 'Africa', incomeLevel: 'lower-middle', population: 1136455 },
  { id: 'c-guy', code: 'GUY', name: 'Guyana', region: 'Latin America', incomeLevel: 'upper-middle', population: 813834 },
  { id: 'c-sur', code: 'SUR', name: 'Suriname', region: 'Latin America', incomeLevel: 'upper-middle', population: 623236 },
  { id: 'c-cog', code: 'COG', name: 'Republic of the Congo', region: 'Africa', incomeLevel: 'lower-middle', population: 6106869 },
  { id: 'c-gnb', code: 'GNB', name: 'Guinea-Bissau', region: 'Africa', incomeLevel: 'low', population: 2150842 },
  { id: 'c-ton', code: 'TON', name: 'Tonga', region: 'Oceania', incomeLevel: 'upper-middle', population: 107773 },
  { id: 'c-atg', code: 'ATG', name: 'Antigua and Barbuda', region: 'Latin America', incomeLevel: 'high', population: 94298 },
  { id: 'c-dma', code: 'DMA', name: 'Dominica', region: 'Latin America', incomeLevel: 'upper-middle', population: 72737 },
  { id: 'c-lca', code: 'LCA', name: 'Saint Lucia', region: 'Latin America', incomeLevel: 'upper-middle', population: 180251 },
  { id: 'c-kna', code: 'KNA', name: 'Saint Kitts and Nevis', region: 'Latin America', incomeLevel: 'high', population: 47755 },
  { id: 'c-grd', code: 'GRD', name: 'Grenada', region: 'Latin America', incomeLevel: 'upper-middle', population: 126183 },
  { id: 'c-plw', code: 'PLW', name: 'Palau', region: 'Oceania', incomeLevel: 'high', population: 18055 },
  { id: 'c-wsm', code: 'WSM', name: 'Samoa', region: 'Oceania', incomeLevel: 'upper-middle', population: 225681 },
  { id: 'c-mhl', code: 'MHL', name: 'Marshall Islands', region: 'Oceania', incomeLevel: 'upper-middle', population: 41996 },
  { id: 'c-tuv', code: 'TUV', name: 'Tuvalu', region: 'Oceania', incomeLevel: 'upper-middle', population: 11396 },
  { id: 'c-nru', code: 'NRU', name: 'Nauru', region: 'Oceania', incomeLevel: 'high', population: 12668 },
  { id: 'c-stp', code: 'STP', name: 'São Tomé and Príncipe', region: 'Africa', incomeLevel: 'lower-middle', population: 231856 },
  { id: 'c-smr', code: 'SMR', name: 'San Marino', region: 'Europe', incomeLevel: 'high', population: 33642 },
  { id: 'c-and', code: 'AND', name: 'Andorra', region: 'Europe', incomeLevel: 'high', population: 80088 },
  { id: 'c-gin', code: 'GIN', name: 'Guinea', region: 'Africa', incomeLevel: 'low', population: 14754778 },
  { id: 'c-tgo', code: 'TGO', name: 'Togo', region: 'Africa', incomeLevel: 'low', population: 9053799 },
  { id: 'c-cpv', code: 'CPV', name: 'Cape Verde', region: 'Africa', incomeLevel: 'lower-middle', population: 598682 },
  { id: 'c-com', code: 'COM', name: 'Comoros', region: 'Africa', incomeLevel: 'lower-middle', population: 852075 },
  { id: 'c-syc', code: 'SYC', name: 'Seychelles', region: 'Africa', incomeLevel: 'high', population: 107660 },
  { id: 'c-bhs', code: 'BHS', name: 'Bahamas', region: 'Latin America', incomeLevel: 'high', population: 412623 },
]

