/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CustomIndexRouteImport } from './routes/custom-index'
import { Route as TrendsRouteImport } from './routes/trends'
import { Route as CountryRouteImport } from './routes/country'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RankingsIndexRouteImport } from './routes/rankings/index'
import { Route as RankingsDomainIndexRouteImport } from './routes/rankings/$domain/index'
import { Route as RankingsDomainIndexIdRouteImport } from './routes/rankings/$domain/$indexId'

const CustomIndexRoute = CustomIndexRouteImport.update({
  id: '/custom-index',
  path: '/custom-index',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendsRoute = TrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => rootRouteImport,
} as any)
const CountryRoute = CountryRouteImport.update({
  id: '/country',
  path: '/country',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsIndexRoute = RankingsIndexRouteImport.update({
  id: '/rankings/',
  path: '/rankings/',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsDomainIndexRoute = RankingsDomainIndexRouteImport.update({
  id: '/rankings/$domain/',
  path: '/rankings/$domain/',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsDomainIndexIdRoute = RankingsDomainIndexIdRouteImport.update({
  id: '/rankings/$domain/$indexId',
  path: '/rankings/$domain/$indexId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/country': typeof CountryRoute
  '/custom-index': typeof CustomIndexRoute
  '/trends': typeof TrendsRoute
  '/rankings': typeof RankingsIndexRoute
  '/rankings/$domain/$indexId': typeof RankingsDomainIndexIdRoute
  '/rankings/$domain': typeof RankingsDomainIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/country': typeof CountryRoute
  '/custom-index': typeof CustomIndexRoute
  '/trends': typeof TrendsRoute
  '/rankings': typeof RankingsIndexRoute
  '/rankings/$domain/$indexId': typeof RankingsDomainIndexIdRoute
  '/rankings/$domain': typeof RankingsDomainIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/country': typeof CountryRoute
  '/custom-index': typeof CustomIndexRoute
  '/trends': typeof TrendsRoute
  '/rankings/': typeof RankingsIndexRoute
  '/rankings/$domain/$indexId': typeof RankingsDomainIndexIdRoute
  '/rankings/$domain/': typeof RankingsDomainIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compare'
    | '/country'
    | '/custom-index'
    | '/trends'
    | '/rankings'
    | '/rankings/$domain/$indexId'
    | '/rankings/$domain'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compare'
    | '/country'
    | '/custom-index'
    | '/trends'
    | '/rankings'
    | '/rankings/$domain/$indexId'
    | '/rankings/$domain'
  id:
    | '__root__'
    | '/'
    | '/compare'
    | '/country'
    | '/custom-index'
    | '/trends'
    | '/rankings/'
    | '/rankings/$domain/$indexId'
    | '/rankings/$domain/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompareRoute: typeof CompareRoute
  CountryRoute: typeof CountryRoute
  CustomIndexRoute: typeof CustomIndexRoute
  TrendsRoute: typeof TrendsRoute
  RankingsIndexRoute: typeof RankingsIndexRoute
  RankingsDomainIndexIdRoute: typeof RankingsDomainIndexIdRoute
  RankingsDomainIndexRoute: typeof RankingsDomainIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/custom-index': {
      id: '/custom-index'
      path: '/custom-index'
      fullPath: '/custom-index'
      preLoaderRoute: typeof CustomIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trends': {
      id: '/trends'
      path: '/trends'
      fullPath: '/trends'
      preLoaderRoute: typeof TrendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/country': {
      id: '/country'
      path: '/country'
      fullPath: '/country'
      preLoaderRoute: typeof CountryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings/': {
      id: '/rankings/'
      path: '/rankings'
      fullPath: '/rankings'
      preLoaderRoute: typeof RankingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings/$domain/': {
      id: '/rankings/$domain/'
      path: '/rankings/$domain'
      fullPath: '/rankings/$domain'
      preLoaderRoute: typeof RankingsDomainIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings/$domain/$indexId': {
      id: '/rankings/$domain/$indexId'
      path: '/rankings/$domain/$indexId'
      fullPath: '/rankings/$domain/$indexId'
      preLoaderRoute: typeof RankingsDomainIndexIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompareRoute: CompareRoute,
  CountryRoute: CountryRoute,
  CustomIndexRoute: CustomIndexRoute,
  TrendsRoute: TrendsRoute,
  RankingsIndexRoute: RankingsIndexRoute,
  RankingsDomainIndexIdRoute: RankingsDomainIndexIdRoute,
  RankingsDomainIndexRoute: RankingsDomainIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
