/**
 * Real GDP Growth Rate Data
 * Source: IMF World Economic Outlook - NGDP_RPCH
 * https://www.imf.org/external/datamapper/NGDP_RPCH@WEO
 * 
 * Auto-generated by scripts/fetch-imf-gdp-growth.ts
 * Last updated: 2025-12-25T01:57:16.029Z
 */

import { realGdpGrowthRankings2010 } from './2010'
import { realGdpGrowthRankings2011 } from './2011'
import { realGdpGrowthRankings2012 } from './2012'
import { realGdpGrowthRankings2013 } from './2013'
import { realGdpGrowthRankings2014 } from './2014'
import { realGdpGrowthRankings2015 } from './2015'
import { realGdpGrowthRankings2016 } from './2016'
import { realGdpGrowthRankings2017 } from './2017'
import { realGdpGrowthRankings2018 } from './2018'
import { realGdpGrowthRankings2019 } from './2019'
import { realGdpGrowthRankings2020 } from './2020'
import { realGdpGrowthRankings2021 } from './2021'
import { realGdpGrowthRankings2022 } from './2022'
import { realGdpGrowthRankings2023 } from './2023'
import { realGdpGrowthRankings2024 } from './2024'
import { realGdpGrowthRankings2025 } from './2025'

export const realGdpGrowthIndex = {
  id: 'idx-real-gdp-growth',
  name: 'Real GDP Growth Rate',
  shortName: 'GDP Growth',
  domainId: 'd-economy',
  source: 'IMF World Economic Outlook',
  sourceUrl: 'https://www.imf.org/external/datamapper/NGDP_RPCH@WEO',
  methodology:
    'Annual percentage change in real gross domestic product (GDP). Real GDP is measured in constant prices, which removes the effects of inflation. Data is compiled from national statistical sources, IMF staff estimates, and projections.',
  updateFrequency: 'semi-annual',
  scoreMin: -60,
  scoreMax: 100,
  higherIsBetter: true,
  lastUpdated: new Date('2025-12-25'),
  unit: 'percent',
}

// Combined rankings for seeding (all years, most recent first)
export const realGdpGrowthRankings = [
  ...realGdpGrowthRankings2025,
  ...realGdpGrowthRankings2024,
  ...realGdpGrowthRankings2023,
  ...realGdpGrowthRankings2022,
  ...realGdpGrowthRankings2021,
  ...realGdpGrowthRankings2020,
  ...realGdpGrowthRankings2019,
  ...realGdpGrowthRankings2018,
  ...realGdpGrowthRankings2017,
  ...realGdpGrowthRankings2016,
  ...realGdpGrowthRankings2015,
  ...realGdpGrowthRankings2014,
  ...realGdpGrowthRankings2013,
  ...realGdpGrowthRankings2012,
  ...realGdpGrowthRankings2011,
  ...realGdpGrowthRankings2010,
]

export const totalCountries = 196

// Re-export year-specific data for direct access
export { realGdpGrowthRankings2025 } from './2025'
export { realGdpGrowthRankings2024 } from './2024'
export { realGdpGrowthRankings2023 } from './2023'
export { realGdpGrowthRankings2022 } from './2022'
export { realGdpGrowthRankings2021 } from './2021'
export { realGdpGrowthRankings2020 } from './2020'
export { realGdpGrowthRankings2019 } from './2019'
export { realGdpGrowthRankings2018 } from './2018'
export { realGdpGrowthRankings2017 } from './2017'
export { realGdpGrowthRankings2016 } from './2016'
export { realGdpGrowthRankings2015 } from './2015'
export { realGdpGrowthRankings2014 } from './2014'
export { realGdpGrowthRankings2013 } from './2013'
export { realGdpGrowthRankings2012 } from './2012'
export { realGdpGrowthRankings2011 } from './2011'
export { realGdpGrowthRankings2010 } from './2010'
